package dubby.server.userservice.util.constants;
/**
 * Here lies all app constants
 */
public enum AppConstant {

    USER_REGISTERED_MESSAGE,
    BAD_EMAIL_FORMAT_MESSAGE,
    BAD_MOBILE_NUMBER_MESSAGE,
    EMAIL_IN_USE_MESSAGE,
    USERNAME_TAKEN_MESSAGE,
    EMAIL_NOT_SENT_MESSAGE,
    MOBILE_NUMBER_IN_USE_MESSAGE,
    CONTACT_DETAILS_REQUIRED_MESSAGE,
    VERIFICATION_REASON_MESSAGE,
    VERIFY_EMAIL_PATH_SERVICE,
    UNRECOGNIZED_IP_MESSAGE,
    IP_ADDRESS_REGEX,
//    DATABASE_URL,
//    DATABASE_USERNAME,
//    DATABASE_PASSWORD,

}
